version: '3.8'
services:
  postgresql:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
      POSTGRES_SCHEMA: demo
    ports:
      - "5430:5432"
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
