micronaut:
  application:
    name: demo

# PostgresSQL
datasources:
  default:
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
    dialect: POSTGRES
    pooled: true
    maximum-pool-size: 10
    minimum-idle: 10
    initial-size: 10
    max-lifetime: 600000
    idle-timeout: 300000
    leak-detection-threshold: 20000

test-resources:
  containers:
    postgres:
      image-name: postgres:16.2
      username: postgres
      password: postgres
      db-name: demo

logger:
  levels:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
